### ISSUE TITLE
New keeper file: validator.go

### ISSUE THREAD

**Issue by prestwich** [summa-tx/relays#21]
Should validate SPV Inclusion Proofs

The solidity looks like this. Use the Proof struct from Bitcoin SPV.
```
    function _checkInclusion(
        bytes memory _header,
        bytes memory _proof,
        uint256 _index,
        bytes32 _txid,
        uint256 _requestID
    ) internal view returns (bool) {
        require(
            ValidateSPV.prove(
                _txid,
                _header.extractMerkleRootLE().toBytes32(),
                _proof,
                _index),
            "Bad inclusion proof");

        bytes32 _headerHash = _header.hash256();
        bytes32 _GCD = getLastReorgCommonAncestor();

        require(
            _isAncestor(
                _headerHash,
                _GCD,
                240),
            "GCD does not confirm header");
        uint8 _numConfs = requests[_requestID].numConfs;
        require(
            _getConfs(_headerHash) >= _numConfs,
            "Insufficient confirmations");

        return true;
    }
```

**Comment by ErinHales** [comment]
Do I need to check the number of confirmations?  If so, how would I do that?

**Comment by prestwich** [comment]
`_getConfs` should be `findHeight(bestKnownDigest) - findHeight(header)`

**Comment by prestwich** [comment]
`uint8 _numConfs = requests[_requestID].numConfs` should use the getter from #22 to laod

if you want to ship this first, just return `getConfs` and we'll fill in the check later

**Comment by ErinHales** [comment]
Ok, I added a todo and will come back to it after addressing #22.  Let's hold off on merging this until it is finished.

**Comment by ErinHales** [comment]
> `_getConfs` should be `findHeight(bestKnownDigest) - findHeight(header)`

How do I find the height of the `bestKnownDigest`?  I know I can just do `header.Height` for the Bitcoin header.

**Comment by prestwich** [comment]
> How do I find the height of the bestKnownDigest? I know I can just do header.Height for the Bitcoin header.

use `GetHeader` to load the header from the store, read the `Height` from there
