### ISSUE TITLE
New Type: Proof Request

### ISSUE THREAD

**Issue by prestwich** [summa-tx/relays#22]
New file: `types/requests.go`

- [x] implement the type
- [x] implement JSON (de)serialization for the type

New file: `keeper/requests.go`
- [x] new prefix store for requests
- [x] Getter for requests
- [x] Setter for requests

New MsgType: 
- [x] MsgNewRequest -- validate a request and store it indexed by ID

New QueryType
- [x] Get Request by ID

Solidity example of struct:
```
    enum RequestStates { ACTIVE, CLOSED }

    struct ProofRequest {
        bytes32 spends;         // hash of the UTXO it spends
        bytes32 pays;           // hash of the output script that it pays
        uint64 paysValue;       // minimum output value 
        RequestStates state;    // is it active?
        uint8 numConfs;         // how many confs does the user want?
    }
```

**Comment by ErinHales** [comment]
How should I validate a request?  And what should I use for the ID?

**Comment by prestwich** [comment]
Use a counter for the ID. store the last used one and increment it when a new one comes in

for validating a request, we want the user to provide a 36-byte outpoint for spends, and then we store a 32-byte digest of the outpoint

the pays should be any number of bytes (up to 50), and we store the 32-byte digest of it

after storing it, emit an event like this:
```
        emit NewProofRequest(msg.sender, _requestID, _paysValue, _spends, _pays);
```
