### ISSUE TITLE
Basic Integration testing script

### ISSUE THREAD

**Issue by prestwich** [summa-tx/relays#29]
A script that boots up a chain, runs through a pre-defined flow, and shuts down. Similar to the IBC demo script.

- minimize required user input
- send key messages
- check results 

relies on #28

**Comment by prestwich** [comment]
https://tutorials.cosmos.network/nameservice/tutorial/22-build-run.html

**Comment by prestwich** [comment]
https://github.com/cosmos/gaia/blob/cwgoes/ibc-demo-fixes/ibc-demo.sh

**Comment by emaG3m** [comment]
https://github.com/summa-tx/relays/pull/57
