### ISSUE TITLE
queries

### ISSUE THREAD

**Issue by prestwich** [summa-tx/relays#4]
- [x] isMostRecentAncestor
- [x] getRelayGenesis
- [x] getLastReorgCommonAncestor
- [x] ~~findHeight~~ not needed b/c header objects store authenticated height now
- [x] findAncestor
- [x] isAncestor
- [x] heaviestFromAncestor

**Comment by ErinHales** [comment]
Are `FindHeight` and `IsMostRecentAncestor` under different names in golang?  I can't find them.

**Comment by prestwich** [comment]
it's not needed. instead, when it's needed, do `GetHeader` and read the `Height`

**Comment by prestwich** [comment]
closed in #9
