### ISSUE TITLE
Document public interface

### ISSUE THREAD

**Issue by prestwich** [summa-tx/relays#44]
CLI and REST documentation

**Comment by prestwich** [comment]
This is mostly addressed by the README. Trying to think what else would be useful

**Comment by prestwich** [comment]
related: #72

**Comment by ErinHales** [comment]
It looks like these files are already pretty well documented.  Did you have any examples of what else needed documentation?

**Comment by prestwich** [comment]
Generally I'd just like more information in READMEs, etc. about what the relay does and how to access its features. This can be mostly focused on the CLI and REST interfaces

**Comment by prestwich** [comment]
I think now that #72 is closed, the last piece here is some basic REST documentation.

**Comment by ErinHales** [comment]
Ok, I got distracted working on some other stuff.  I've got a PR open with what I'd been working on, I've got a few more things to add.
