### ISSUE TITLE
Support empty `Spends` and `Pays`

### ISSUE THREAD

**Issue by prestwich** [summa-tx/relays#47]
`keeper/request.go` hashes the Spends and Pays even if they're empty.
https://github.com/summa-tx/relays/blob/golang/golang/x/relay/keeper/requests.go#L30-L31

If `Spends` is empty, then `spendsDigest` should `btcspv.Hash256Digest{}`
Same for `Pays` and `paysDigest`.

Then later in the file:
- `hasPays` should be `req.Pays != btcspv.Hash256Digest{}`
    - https://github.com/summa-tx/relays/blob/golang/golang/x/relay/keeper/requests.go#L150
- `hasSpends` should be `req.Spends != btcspv.Hash256Digest{}`
    - https://github.com/summa-tx/relays/blob/golang/golang/x/relay/keeper/requests.go#L165

**Comment by emaG3m** [comment]
addressed https://github.com/summa-tx/relays/pull/45/files
