### ISSUE TITLE
 Show height for best known digest and updatedAt

### ISSUE THREAD

**Issue by barbaraliau** [summa-tx/relays#80]
See Current Block section for how height works

Updated At should be a time stamp. Will need to filter this for display.

**Comment by dominiquejane** [comment]
@barbaraliau Where is the Current Block section? Is it just in the dashboard readme?

**Comment by dominiquejane** [comment]
@barbaraliau What format do we want for the timestamp?

**Comment by barbaraliau** [comment]
It's the first section of the dashboard UI.

Timestamp UI: `HH:MM:SS - DD Mon`
