### ISSUE TITLE
Update server check banner

### ISSUE THREAD

**Issue by barbaraliau** [summa-tx/relays#85]
This used to check for a connection to the web3 server. We don't have that anymore. This should check to see if the local relay is running by sending a REST query.

If a successful response is received, show "Connected to relay" on a green background. Always show this banner to indicate connection status. Connection status is different than health status (connection == relay is running and we are connected; health == connected, but data is off)

**Comment by ErinHales** [comment]
How often do you want to send a connection test query?

**Comment by barbaraliau** [comment]
Every minute

**Comment by ErinHales** [comment]
Oh, that is actually perfect!  We're already doing queries every minute
